name: 'Comment Catcher'
description: 'Detects outdated code comments in TypeScript/JavaScript projects using AI analysis'
author: 'zachicecreamcohn'
branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for posting PR comments'
    required: true
  base-branch:
    description: 'Base branch to compare against'
    required: false
    default: 'main'
  depth:
    description: 'Dependency graph depth to traverse'
    required: false
    default: '3'
  anthropic-api-key:
    description: 'Anthropic API key for Claude AI'
    required: true
  anthropic-base-url:
    description: 'Anthropic API base URL (for custom endpoints)'
    required: false
    default: 'https://api.anthropic.com'
  github-api-url:
    description: 'GitHub API URL (for GitHub Enterprise)'
    required: false
    default: 'https://api.github.com'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install comment-catcher
      shell: bash
      run: npm install -g comment-catcher

    - name: Run comment-catcher and post results
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        ANTHROPIC_BASE_URL: ${{ inputs.anthropic-base-url }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        DEPTH: ${{ inputs.depth }}
        GITHUB_API_URL: ${{ inputs.github-api-url }}
      run: |
        node ${{ github.action_path }}/scripts/run-and-comment.js
